aarch64: # target cpu
  cpu_type: "aarch64"
  tarball_url: "https://toolchains.bootlin.com/downloads/releases/toolchains/aarch64/tarballs/aarch64--glibc--bleeding-edge-2018.07-1.tar.bz2"
  tool_perfix: "aarch64-linux"
  strip_perfix: "aarch64--glibc--bleeding-edge-2018.07-1"
  buildroot_dir: "aarch64-buildroot-linux-gnu"
  toolchain_id: "bootlin_aarch64_toolchain"
  glibc_version: "glibc_2.27.57"
  gcc_version: "8.1.0"

armv7:
  cpu_type: "armeabi-v7a"
  tarball_url: "https://toolchains.bootlin.com/downloads/releases/toolchains/armv7-eabihf/tarballs/armv7-eabihf--glibc--bleeding-edge-2018.07-1.tar.bz2"
  tool_perfix: "arm-linux"
  strip_perfix: "armv7-eabihf--glibc--bleeding-edge-2018.07-1"
  buildroot_dir: "arm-buildroot-linux-gnueabihf"
  toolchain_id: "bootlin_arm_toolchain"
  glibc_version: "glibc_2.27.57"
  gcc_version: "8.1.0"

x86_64:
  cpu_type: "x86_64"
  tarball_url: "https://toolchains.bootlin.com/downloads/releases/toolchains/x86-64-core-i7/tarballs/x86-64-core-i7--glibc--bleeding-edge-2018.07-1.tar.bz2"
  tool_perfix: "x86_64-linux"
  strip_perfix: "x86-64-core-i7--glibc--bleeding-edge-2018.07-1"
  buildroot_dir: "x86_64-buildroot-linux-gnu"
  toolchain_id: "bootlin_x86_64_toolchain"
  glibc_version: "glibc_2.27.57"
  gcc_version: "8.1.0"

i686:
  cpu_type: "i686"
  tarball_url: "https://toolchains.bootlin.com/downloads/releases/toolchains/x86-i686/tarballs/x86-i686--glibc--bleeding-edge-2018.07-1.tar.bz2"
  tool_perfix: "i686-linux"
  strip_perfix: "x86-i686--glibc--bleeding-edge-2018.07-1"
  buildroot_dir: "i686-buildroot-linux-gnu"
  toolchain_id: "bootlin_i686_toolchain"
  glibc_version: "glibc_2.27.57"
  gcc_version: "8.1.0"

esp32_64:
  cpu_type: "xtensa"
  tarball_url: "https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz"
  tool_perfix: "xtensa-esp32-elf"
  strip_perfix: "xtensa-esp32-elf"
  buildroot_dir: "xtensa-esp32-elf"
  toolchain_id: "xtensa_esp32_elf_linux64"
  glibc_version: "glibc_2.27.57"
  gcc_version: "5.2.0"

armv6:
  cpu_type: "armv6"
  tarball_url: "https://github.com/raspberrypi/tools/archive/49719d5544cd33b8c146235e1420f68cd92420fe.tar.gz"
  tool_perfix: "arm-linux-gnueabihf"
  strip_perfix: "tools-49719d5544cd33b8c146235e1420f68cd92420fe"
  buildroot_dir: "rpi_arm_toolchain/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/arm-linux-gnueabihf"
  toolchain_id: "rpi_arm_toolchain"
  glibc_version: "glibc_2.19"
  gcc_version: "4.9.3"
